<?php
/**
 * @author      PagarMe Modules Team <modules@pagar.me>
 * @copyright   2018 PagarMe (http://pagar.me)
 * @license     http://pagar.me Copyright
 *
 * @link        http://pagar.me
 *
 * @codingStandardsIgnoreFile
 *
 * @var \PagarMe\PagarMe\Block\Payment\Info\Billet $block
 * @see \PagarMe\PagarMe\Block\Payment\Info\Billet
 */
$specificInfo = $block->getSpecificInformation();
?>

<?php echo $block->escapeHtml($block->getMethod()->getTitle()); ?>

<?php if ($specificInfo): ?>
    <table class="data-table admin__table-secondary">
        <?php foreach ($specificInfo as $label => $value):?>
            <tr>
                <?php if($label === (string) __('Print Billet')): ?>
                    <td colspan="2">
                        <a class="action-default" target="_blank" href="<?php echo $value?>"><?php echo __('Print Billet') ?></a>
                    </td>
                    <?php continue;?>
                <?php endif;?>
                <th><?php echo $block->escapeHtml($label)?>:</th>
                <td>
                    <?php /* @noEscape */ echo nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true))));?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif;?>

<?php echo $block->getChildHtml()?>